
_default:
    just --list

# Set the project name to this directory's name (run once after flake init)
init:
    sed -i "s/changeme/{{file_name(justfile_directory())}}/g" secretspec.toml Cargo.toml

# Build the project
build:
    cargo build

# Run the main program
run:
    cargo run

# Lint with clippy
lint:
    cargo clippy --all-targets

# Format all sources
fmt:
    cargo fmt

