
_default:
    just --list

# Set the project name to this directory's name (run once after flake init)
init:
    sed -i "s/changeme/{{file_name(justfile_directory())}}/g" secretspec.toml

# Build a debug APK
build:
    ./gradlew assembleDebug

# Install the debug build on a connected device
install:
    ./gradlew installDebug

# List connected devices
devices:
    adb devices

