{ pkgs, ... }: {
    environment.systemPackages = with pkgs; [
        python312
        rustup
        cargo
        clippy
        rustc
        gcc
        ripgrep
        signal-desktop
        obsidian
        flavours
        alacritty
        firefox
        wofi
        syncthing
        keepassxc
        dunst
        bspwm
        git
        docker
        qt6.qtwayland
        libsForQt5.qt5.qtwayland
        libsForQt5.qtstyleplugins
        wl-clipboard
        cliphist
        grim
        hyprpaper
        libnotify
        swayidle
        swaylock-effects
        pavucontrol
        vlc
        psmisc
        networkmanagerapplet
    ];
}
